# Generated by Django 4.2.7 on 2023-11-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiview_generic', '0002_author_book_genre_profile_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
        migrations.AddField(
            model_name='order',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='apiview_generic.genre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_profile',
            field=models.CharField(max_length=100),
        ),
    ]
